"""
Project: Stock Price Predictor v2
Package: src
Filename: data_preprocessing.py
Description: Data preprocessing and validation module. Consolidates multi-stage 
             data cleaning routines, left-join feature alignment, feature matrix slicing, 
             and missing data resolution strategies for training and inference pipelines.
Author: Kartik Kant (AI/ML Engineer)
"""

import pandas as pd
import numpy as np
from typing import List, Tuple, Optional, Any
from src.logger import get_logger

# Initialize centralized logging context for pipeline tracing
logger = get_logger(__name__)


# ==========================================
# DEFENSIVE DATA FRAME VALIDATION ROUTINES
# ==========================================
def validate_dataframe(df: Any, name: str = "DataFrame") -> None:
    """
    Validates structural validity of input arguments to protect downstream execution pipelines.

    Args:
        df (Any): Operational object to validate.
        name (str): Label placeholder utilized for debugging outputs and exceptions.

    Raises:
        ValueError: If input object is missing, structurally non-tabular, or blank.
    """
    if df is None:
        raise ValueError(f"{name} cannot be None")

    if not isinstance(df, pd.DataFrame):
        raise ValueError(f"{name} must be a pandas DataFrame, got {type(df)}")

    if df.empty:
        raise ValueError(f"{name} cannot be empty")


# ==========================================
# TIME-SERIES MULTI-SOURCE MERGING LAYER
# ==========================================
def merge_stock_sentiment(
    stock_data: pd.DataFrame,
    daily_sentiment: Optional[pd.DataFrame],
    fill_sentiment: float = 0.0
) -> pd.DataFrame:
    """
    Coordinates left-join data consolidation routines combining temporal price feeds 
    with natural language text analysis indicators.

    Args:
        stock_data (pd.DataFrame): Time-series matrix containing OHLCV and indicator metrics.
        daily_sentiment (Optional[pd.DataFrame]): Tabular data frame containing computed NLP metrics.
        fill_sentiment (float): Default substitution value representing a neutral market state.

    Returns:
        pd.DataFrame: Clean, aligned, timestamp-indexed processing matrix.

    Raises:
        ValueError: If base historical price structures are invalid or empty after processing.
    """
    validate_dataframe(stock_data, "stock_data")
    logger.debug(f"Merging stock data ({len(stock_data)} rows)")

    # Execution fallback path to handle deployment environments where text indicators are missing
    if daily_sentiment is None or daily_sentiment.empty:
        logger.warning("No sentiment data provided, proceeding with stock data only")
        result = stock_data.copy()
        result['Sentiment'] = fill_sentiment
        return result

    if not isinstance(daily_sentiment, pd.DataFrame):
        logger.error(f"daily_sentiment must be DataFrame, got {type(daily_sentiment)}")
        raise ValueError("daily_sentiment must be a pandas DataFrame")

    stock_data = stock_data.copy()

    # Enforce standard datetime index formatting prior to running calendar lookups
    if not isinstance(stock_data.index, pd.DatetimeIndex):
        stock_data.index = pd.to_datetime(stock_data.index)

    stock_data['Date'] = stock_data.index.date

    daily_sentiment = daily_sentiment.copy()
    if isinstance(daily_sentiment.index, pd.DatetimeIndex):
        daily_sentiment['Date'] = daily_sentiment.index.date
    else:
        logger.warning("Sentiment index is not DatetimeIndex, using NaT")
        daily_sentiment['Date'] = pd.NaT

    # Drop explicit indexes to circumvent layout duplication anomalies during merging operations
    stock_data = stock_data.reset_index(drop=True)
    daily_sentiment = daily_sentiment.reset_index(drop=True)

    # Convert temporal structural series to standard datetime vector spaces
    stock_data['Date'] = pd.to_datetime(stock_data['Date'])
    daily_sentiment['Date'] = pd.to_datetime(daily_sentiment['Date'])

    # Execute left-join merge to lock data matrix constraints around actual trade records
    data = pd.merge(stock_data, daily_sentiment, on='Date', how='left')

    # Re-establish standard DatetimeIndex layout mapping required for time-series splits
    data = data.set_index('Date')

    # Resolve blank entries by setting missing records to neutral indices
    data['Sentiment'] = data['Sentiment'].fillna(fill_sentiment)

    # Purge NaN entries generated by early rolling technical overlays
    initial_count = len(data)
    data = data.dropna()
    dropped_count = initial_count - len(data)

    if dropped_count > 0:
        logger.info(f"Dropped {dropped_count} rows with NaN values after merge")

    if data.empty:
        logger.error("No data available after merging and cleaning")
        raise ValueError("No data available after merging and cleaning")

    logger.debug(f"Merged data shape: {data.shape}")
    return data


# ==========================================
# SCHEMA VERIFICATION VALIDATOR
# ==========================================
def validate_features(
    data: pd.DataFrame,
    required_features: List[str]
) -> Tuple[bool, List[str]]:
    """
    Performs structural property reviews on matrices to match active settings properties.

    Args:
        data (pd.DataFrame): Target time-series dataframe being evaluated.
        required_features (List[str]): Feature label collections required by the LSTM model.

    Returns:
        Tuple[bool, List[str]]: (Boolean state flag, Array string block identifying unmatched column names)

    Raises:
        ValueError: If dataset elements or feature strings are structurally empty.
    """
    if data is None or data.empty:
        raise ValueError("data cannot be empty")

    if not required_features:
        raise ValueError("required_features cannot be empty")

    if not isinstance(required_features, list):
        raise ValueError("required_features must be a list")

    # Isolate missing feature requirements by executing comparison loops
    missing = [f for f in required_features if f not in data.columns]
    is_valid = len(missing) == 0

    if not is_valid:
        logger.error(f"Missing features: {missing}")

    return is_valid, missing


# ==========================================
# FEATURE EXTRACTION & SHAPING ROUTINES
# ==========================================
def prepare_features(
    data: pd.DataFrame,
    features: List[str],
    target_feature: str
) -> Tuple[pd.DataFrame, pd.DataFrame, List[str]]:
    """
    Slices historical master tracking tables down into independent feature matrices and targets.

    Args:
        data (pd.DataFrame): Clean time-series panel matrix data.
        features (List[str]): Independent variable string list configurations defining matrix X.
        target_feature (str): Target pricing column identifier tracking matrix y.

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame, List[str]]: (Matrix X features, Matrix y labels, Features schema)

    Raises:
        ValueError: If validation parameters cross logical constraints or properties are missing.
    """
    validate_dataframe(data, "data")

    if not features:
        raise ValueError("features cannot be empty")

    if not isinstance(features, list):
        raise ValueError("features must be a list")

    if not target_feature:
        raise ValueError("target_feature cannot be empty")

    logger.debug(f"Preparing features: {features}")

    # Enforce alignment between active data frame layouts and configuration schemas
    is_valid, missing = validate_features(data, features)
    if not is_valid:
        raise ValueError(f"Missing features: {missing}")

    if target_feature not in data.columns:
        raise ValueError(f"Target feature '{target_feature}' not found in data")

    # Isolate vector coordinates to form model processing inputs
    X = data[features]
    y = data[[target_feature]]

    logger.debug(f"X shape: {X.shape}, y shape: {y.shape}")

    return X, y, features


# ==========================================
# MISSING DATA RESOLUTION LAYER
# ==========================================
def fill_missing_values(
    data: pd.DataFrame,
    fill_method: str = 'ffill_bfill'
) -> pd.DataFrame:
    """
    Resolves data matrix holes by executing explicit time-series sequence propagation.

    Args:
        data (pd.DataFrame): Evaluation time-series matrix containing NaN entries.
        fill_method (str): Operational routine configuration selector ('ffill_bfill', 'ffill', 'bfill', 'drop').

    Returns:
        pd.DataFrame: Completed data matrix with localized null entries resolved.

    Raises:
        ValueError: If target time-series variables are missing or non-existent.
    """
    if data is None:
        raise ValueError("data cannot be None")

    if data.empty:
        return data

    # Fallback to standard validation bounds if execution strings are malformed
    valid_methods = ['ffill_bfill', 'ffill', 'bfill', 'drop']
    if fill_method not in valid_methods:
        logger.warning(f"Unknown fill method '{fill_method}', using ffill_bfill")
        fill_method = 'ffill_bfill'

    initial_nan_count = data.isna().sum().sum()

    # Route data transformation loops down the selected algorithmic cleaning track
    if fill_method == 'ffill_bfill':
        data = data.ffill().bfill()
    elif fill_method == 'ffill':
        data = data.ffill()
    elif fill_method == 'bfill':
        data = data.bfill()
    elif fill_method == 'drop':
        data = data.dropna()

    remaining_nan_count = data.isna().sum().sum()

    if remaining_nan_count > 0:
        logger.warning(f"Still have {remaining_nan_count} NaN values after filling")

    filled_count = initial_nan_count - remaining_nan_count
    if filled_count > 0:
        logger.info(f"Filled {filled_count} NaN values using '{fill_method}'")

    return data


# ==========================================
# TEMPORAL INDEX ALIGNMENT UTILS
# ==========================================
def create_time_index(
    data: pd.DataFrame,
    date_column: str = 'Date'
) -> pd.DataFrame:
    """
    Standardizes index properties to enforce proper chronological order across code pipelines.

    Args:
        data (pd.DataFrame): Operational time-series data frame.
        date_column (str): Designated target string field map for text date rows.

    Returns:
        pd.DataFrame: Consolidated data matrix locked to a proper DatetimeIndex.

    Raises:
        ValueError: If baseline processing components are missing.
    """
    if data is None:
        raise ValueError("data cannot be None")

    data = data.copy()

    if isinstance(data.index, pd.DatetimeIndex):
        logger.debug("Index is already DatetimeIndex")
        return data

    # Map string parameters into formalized pandas index records if applicable
    if date_column in data.columns:
        data.index = pd.to_datetime(data[date_column])
        data = data.drop(columns=[date_column])
        logger.debug(f"Created DatetimeIndex from column '{date_column}'")
    else:
        logger.warning(f"Date column '{date_column}' not found, using existing index")
        data.index = pd.to_datetime(data.index)

    return data